In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6,7,8]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
l1=[2,3,4,5,'lala',9.02,True]

In [5]:
np.array(l1)

array(['2', '3', '4', '5', 'lala', '9.02', 'True'], dtype='<U32')

In [6]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b=np.array([[[1,3,5],[2,4,6],[5,6,7]]])

In [9]:
b

array([[[1, 3, 5],
        [2, 4, 6],
        [5, 6, 7]]])

In [10]:
np.ndim(a)

2

In [11]:
b.ndim

3

In [12]:
a.size

8

In [13]:
b.size

9

In [14]:
a.shape

(2, 4)

In [15]:
b.shape

(1, 3, 3)

In [16]:
np.random.randint(1,20,(3,3))

array([[ 5,  1,  2],
       [ 6,  9, 12],
       [12, 13, 16]])

In [17]:
np.random.randint(1,10,(2,3,3))

array([[[7, 3, 8],
        [4, 7, 6],
        [5, 4, 7]],

       [[3, 6, 2],
        [1, 8, 8],
        [9, 4, 4]]])

In [18]:
np.random.rand(2,3)

array([[0.41545336, 0.39456327, 0.52305093],
       [0.96478326, 0.1765734 , 0.78458182]])

In [19]:
a1=np.random.randn(4,4)

In [20]:
a1

array([[ 0.90919752,  0.97168716, -0.05160505, -0.52276647],
       [-0.94479157, -0.55903224, -0.26576633, -0.18269903],
       [ 1.05260867,  0.68185441, -0.85807613,  2.1881364 ],
       [ 0.51718709,  0.30391968,  0.62218678,  0.18003014]])

In [21]:
a1.reshape(8,2)

array([[ 0.90919752,  0.97168716],
       [-0.05160505, -0.52276647],
       [-0.94479157, -0.55903224],
       [-0.26576633, -0.18269903],
       [ 1.05260867,  0.68185441],
       [-0.85807613,  2.1881364 ],
       [ 0.51718709,  0.30391968],
       [ 0.62218678,  0.18003014]])

In [22]:
a1.reshape(2,4,2)

array([[[ 0.90919752,  0.97168716],
        [-0.05160505, -0.52276647],
        [-0.94479157, -0.55903224],
        [-0.26576633, -0.18269903]],

       [[ 1.05260867,  0.68185441],
        [-0.85807613,  2.1881364 ],
        [ 0.51718709,  0.30391968],
        [ 0.62218678,  0.18003014]]])

In [23]:
b

array([[[1, 3, 5],
        [2, 4, 6],
        [5, 6, 7]]])

In [24]:
b[:,1:3,1:3]

array([[[4, 6],
        [6, 7]]])

In [25]:
a[:,[1,2]]

array([[2, 3],
       [6, 7]])

In [26]:
a[[0,1] , 1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [28]:
a2=np.random.randint(2,90,(4,4))

In [29]:
a2

array([[30, 64, 69, 60],
       [35, 64, 88, 38],
       [88, 28, 64, 44],
       [ 4, 56, 68, 29]])

In [30]:
a2[a2>60]

array([64, 69, 64, 88, 88, 64, 68])

In [32]:
a2[1,2]=99

In [33]:
a2

array([[30, 64, 69, 60],
       [35, 64, 99, 38],
       [88, 28, 64, 44],
       [ 4, 56, 68, 29]])

In [34]:
a3=np.random.randint(0,3,(3,3))

In [35]:
a4=np.random.randint(0,3,(3,3))

In [36]:
a3

array([[0, 1, 1],
       [0, 2, 1],
       [0, 1, 2]])

In [37]:
a4

array([[0, 2, 1],
       [2, 1, 0],
       [2, 2, 0]])

In [38]:
a3*a4

array([[0, 2, 1],
       [0, 2, 0],
       [0, 2, 0]])

In [40]:
a5=a3@a4

In [41]:
a5

array([[4, 3, 0],
       [6, 4, 0],
       [6, 5, 0]])

In [42]:
a5+100

array([[104, 103, 100],
       [106, 104, 100],
       [106, 105, 100]])

In [43]:
a5*2

array([[ 8,  6,  0],
       [12,  8,  0],
       [12, 10,  0]])

In [45]:
a5/0

C:\Users\user\AppData\Local\Temp\ipykernel_9516\538482321.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a5/0
C:\Users\user\AppData\Local\Temp\ipykernel_9516\538482321.py:1: RuntimeWarning: invalid value encountered in true_divide
  a5/0


array([[inf, inf, nan],
       [inf, inf, nan],
       [inf, inf, nan]])

In [46]:
a5**3

array([[ 64,  27,   0],
       [216,  64,   0],
       [216, 125,   0]], dtype=int32)

In [48]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((4,4))+ np.array([1,2,3,4])

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [57]:
np.array([[1,2,3,4]]).T + np.zeros((4,4))

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [59]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [60]:
np.sqrt(a2)

array([[5.47722558, 8.        , 8.30662386, 7.74596669],
       [5.91607978, 8.        , 9.94987437, 6.164414  ],
       [9.38083152, 5.29150262, 8.        , 6.63324958],
       [2.        , 7.48331477, 8.24621125, 5.38516481]])

In [61]:
np.exp(a2)

array([[1.06864746e+13, 6.23514908e+27, 9.25378173e+29, 1.14200739e+26],
       [1.58601345e+15, 6.23514908e+27, 9.88903032e+42, 3.18559318e+16],
       [1.65163625e+38, 1.44625706e+12, 6.23514908e+27, 1.28516001e+19],
       [5.45981500e+01, 2.09165950e+24, 3.40427605e+29, 3.93133430e+12]])

In [62]:
np.log10(a2)

array([[1.47712125, 1.80617997, 1.83884909, 1.77815125],
       [1.54406804, 1.80617997, 1.99563519, 1.5797836 ],
       [1.94448267, 1.44715803, 1.80617997, 1.64345268],
       [0.60205999, 1.74818803, 1.83250891, 1.462398  ]])

In [68]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [69]:
np.arange(1.2,11.4,2.3)

array([ 1.2,  3.5,  5.8,  8.1, 10.4])

In [71]:
np.linspace(2,3,num=40,retstep=True)

(array([2.        , 2.02564103, 2.05128205, 2.07692308, 2.1025641 ,
        2.12820513, 2.15384615, 2.17948718, 2.20512821, 2.23076923,
        2.25641026, 2.28205128, 2.30769231, 2.33333333, 2.35897436,
        2.38461538, 2.41025641, 2.43589744, 2.46153846, 2.48717949,
        2.51282051, 2.53846154, 2.56410256, 2.58974359, 2.61538462,
        2.64102564, 2.66666667, 2.69230769, 2.71794872, 2.74358974,
        2.76923077, 2.79487179, 2.82051282, 2.84615385, 2.87179487,
        2.8974359 , 2.92307692, 2.94871795, 2.97435897, 3.        ]),
 0.02564102564102564)

In [72]:
np.logspace(2,3, num=10, base=10)

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

In [73]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
import cufflinks as cf
import pandas as pd
import numpy as np
import seaborn as sns

In [82]:
!pip install cufflinks

In [84]:
cf.go_offline()

In [94]:
df=pd.DataFrame(np.random.randn(12,4), columns=['A','B','C','D'], index=['a','b','c','d','e','f','g','h','i','j','k','l'])

In [95]:
df

A         B         C         D
a -0.193268 -2.155911  1.902292  1.257446
b -1.557494  1.023722  0.339629  1.787751
c -0.514459 -0.784597 -0.694994  0.240770
d  0.148245  0.849644 -0.916986 -0.286637
e  0.196570 -0.488058 -0.144178 -0.796608
f -0.531381 -0.879486  0.833966  1.949381
g -1.011959 -0.169020 -1.411029 -1.246688
h  0.034097  1.324056 -0.509095  1.800461
i -0.168194 -0.819689  0.310613  1.010544
j  0.220165  1.908099 -0.954031 -0.415888
k -1.079366  0.288740  0.428134 -0.945937
l  0.871073 -0.008744 -0.747094 -0.578606

In [97]:
df.iplot()

In [98]:
df1=pd.DataFrame(np.random.randint(1,100,(70,2)))

In [99]:
df1

0   1
0   21  12
1   31  66
2   83  94
3   56  77
4   81  38
..  ..  ..
65  53  38
66  55  87
67  73   9
68  45  39
69  19  30

[70 rows x 2 columns]

In [100]:
df1.iplot()

In [104]:
df.iplot(x='A',y='B',mode='markers')

In [106]:
ds=sns.load_dataset('titanic')

In [107]:
ds

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [109]:
ds.iplot(x='age',y='pclass', mode='markers')

In [114]:
ds.iplot(kind='bar',x='survived',y='sex')